//! Step 5 - Use Redux State and Actions in React Components
import React from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { decrement, increment, incrementByAmount } from '../features/counter/counterSlice'

const Counter = () => {
  let count = useSelector(state => state.counter.value); //! (IMP). -> (state => state.counter.value) - is the selector function., we can write the state parameter without (), becoz of single parameter. useSelector() subscribes the store. state is whole redux store and state.counter.value → Actual value needed by component. whenever state value changes, Redux notifies useSelector() and this selector function run again and updates with the new value (If value changed/updated then whole component re render) and updated value stored in count variable which shown on UI as we write in the JSX {count}
  let dispatch = useDispatch(); // dispatch -> Function returned by useDispatch().

  return (
    <>
    <h1>Count: {count}</h1>

    <div>
          {/* Action Creator = increment() */}
        <button onClick={() => dispatch(increment())}>Increment</button>
     
        <button onClick={() => dispatch(decrement())}>Decrement</button>
     
        <button onClick={() => dispatch(incrementByAmount(5))}>Add 5</button>
    </div>
         
    </>
  )
}

export default Counter

//! Now we can use the React-Redux hooks to let React components interact with the Redux store. We can read data from the store with useSelector, and dispatch actions using useDispatch. Create a src/features/counter/Counter.js file with a <Counter> component inside, then import that component into App.js and render it inside of <App>.

/*
! Now, any time you click the "Increment" and "Decrement" buttons:

The corresponding Redux action will be dispatched to the store
The counter slice reducer will see the actions and update its state
The <Counter> component will see the new state value from the store and re-render itself with the new data
*/

/*
! (IMP)
! const count = useSelector(state => state.counter.value);

! (IMP)
? state => state.counter.value is the selector function.
? We can write the state parameter without () because it is a single parameter.
? useSelector() subscribes the component to the Redux store.
? state represents the entire Redux store state.
? state.counter.value is the actual value needed by the component.
? Whenever the Redux store state changes, Redux notifies useSelector().
? Then the selector function runs again and gets the latest value.
? React-Redux compares the previous selected value with the new selected value.
? If the selected value has changed, the component re-renders.
? The updated value is assigned to the count variable and displayed in the UI using {count}.

! The order is:
Store State Changes
        ↓
Redux notifies subscribers
        ↓
Selector function runs again
        ↓
Compare old value vs new value
        ↓
If value changed
        ↓
Component re-renders

! useDispatch()
Hook provided by React Redux.
? Used to get the dispatch function from the Redux store.

! dispatch
Function returned by useDispatch().
? Used to send actions to the Redux store.

! useDispatch() is a React Redux hook that returns the Redux store's dispatch function. dispatch itself is a function used to send actions to the Redux store and trigger state updates.
useDispatch()  --->  dispatch function
   (hook)             (function)

! In counterSlice.jsx
export const counterSlice = createSlice({
    name: 'counter',
    initialState: {
        value: 0
    },

! Understanding state.counter.value
? In Counter.jsx
const count = useSelector(
  (state) => state.counter.value
);

! What is state?

? state is the entire Redux store state.

state = {
  counter: {
    value: 0
  }
}

! Easy Rule
state        → Entire Redux Store

state.counter → Counter Slice State ({ value: 0 })

state.counter.value → Actual value needed by component

! So in:

const count = useSelector(
  (state) => state.counter.value
);

? state = whole Redux store
? counter = slice name/key in the store
? value = property inside that slice's state
? useSelector returns that value and subscribes to changes in it.

! Complete Flow
Button Click
     ↓
dispatch(increment())
     ↓
increment() creates action
     ↓
{ type: "counter/increment" }
     ↓
Store receives action
     ↓
Reducer runs
     ↓
State updates
     ↓
UI re-renders

! dispatch(action) sends an action object to the Redux store, which forwards it to the reducer to update the state.

! What is an Action Creator?
!! An action creator is a function that creates and returns an action object. In Redux Toolkit, action creators are automatically generated by createSlice() and are available through slice.actions.

? the action object is sent to the store through dispatch().
? Action Creator = increment()
Dispatch = dispatch(increment())

? Action = { type: "counter/increment" }
? Action Creator = increment()
? Dispatch = dispatch(increment()) ✅

! Action Creator (generated automatically)
? counterSlice.actions.increment

! which is equivalent to:

function increment() {
  return {
    type: "counter/increment"
  };
}

! Visual Representation
reducers: {
  increment: (state) => {
    state.value++;
  }
}
        │
        │ createSlice()
        ▼

Case Reducer
increment(state)

        +

Action Creator
increment()

!! When you write
? export const { increment } = counterSlice.actions;

!! you are extracting the generated action creator, not the reducer function.

! So later:

? dispatch(increment());

! means:

dispatch({
  type: "counter/increment"
});


? counterSlice.actions.increment → Action Creator (auto-generated)
? increment() → Returns an action object
? dispatch(increment()) → Sends the action to the store

! What is an Action?

An Action is a plain JavaScript object that tells Redux what happened.

Example:

{
  type: "counter/increment"
}

! Meaning:

? "Increment the counter."

! Easy Memory
? actions  → Import in Components → dispatch()

? reducer  → Import in Store → manage state

? increment()  → creates action

? counterReducer → handles action & updates state

! Note - React-Redux is Official library that connects Redux with React components.
! React Redux is the library that allows React components to interact with the Redux store.

! What is React Redux?
! React Redux is the official binding library that connects React components with the Redux store using hooks like useSelector and useDispatch.
*/