//! Step 3 - Create a Redux State Slice
import { createSlice } from "@reduxjs/toolkit";

export const counterSlice = createSlice({
    name: 'counter',
    initialState: {
        value: 0
    },
    reducers: {
        increment: state => {
        // Redux Toolkit allows us to write "mutating" logic in reducers. It
        // doesn't actually mutate the state because it uses the Immer library,
        // which detects changes to a "draft state" and produces a brand new
        // immutable state based off those changes
            state.value += 1
        },
        decrement: state => {
            state.value -= 1
        },
        incrementByAmount: (state, action) => {
            state.value += action.payload
        }
    }
})

// Action creators are generated for each case reducer function
export const {increment, decrement, incrementByAmount} = counterSlice.actions

export default counterSlice.reducer

/*
! createSlice() is a function provided by Redux Toolkit that helps you create:
State
Reducers
Action Creators

all in one place.

? A Slice is a portion (piece) of the Redux Store state along with the reducers and actions that manage that portion.

! Parts of createSlice()

! 1. name
name: "counter"

? Name of the slice.
? Used to generate action types.

! Example:

increment()

! creates:

{
  type: "counter/increment"
}

! 2. initialState
initialState: {
  value: 0
}

? Defines the initial state of the slice.

! 3. reducers
reducers: {
  increment: (state) => {
    state.value += 1;
  }
}

? Contains functions that update the state.
? Redux Toolkit uses Immer, so you can write "mutating" code like state.value += 1.

! What does createSlice() return?
const counterSlice = createSlice({...});

! It returns an object:

{
  name: "counter",
  reducer: function,
  actions: {
    increment,
    decrement
  }
}

! counterSlice.reducer

? Used in the store:

const store = configureStore({
  reducer: {
    counter: counterSlice.reducer
  }
});

! counterSlice.actions

? Used in components:

dispatch(counterSlice.actions.increment());

!!! Immer is a JavaScript library that lets you write code as if you're mutating (changing) state directly, but it actually creates a new immutable state behind the scenes. !!!

? Without Immer (Plain Redux)

! You must return a new object:

const reducer = (state, action) => {
  return {
    ...state,
    value: state.value + 1,
  };
};

!! Redux requires state to be immutable, so you cannot do:

? state.value += 1; // ❌ Not allowed in plain Redux

! With Immer (Redux Toolkit)

! You can write:

increment: (state) => {
  state.value += 1;
}

! It looks like you're changing the state directly, but Immer does this internally:

! You write:
state.value += 1;

! Immer creates:
return {
  ...state,
  value: state.value + 1,
};

! How Immer Works
? Immer creates a draft copy of the state.
? You modify the draft:
? state.value += 1;
? Immer tracks the changes.
? Immer generates a brand-new immutable state.

! Example:

Current State:
{
  value: 0
}

! You write:

state.value += 1;

! Immer produces:

{
  value: 1
}

! The original state is never modified.

Easy Interview Definition

!! Immer is a library used by Redux Toolkit that allows us to write mutable-looking code inside reducers while actually keeping the Redux state immutable. It creates a draft state, tracks changes, and generates a new immutable state automatically.

! Remember
? state.value += 1;
? Looks like mutation ✅
? Actually immutable ✅
? Works because of Immer ✅

That's why Redux Toolkit reducers are much shorter and easier to write than traditional Redux reducers. 🚀

! A draft state is a temporary copy of the current state created by Immer.
!!! A draft state is a temporary copy of the Redux state created by Immer. We can modify the draft directly, and Immer uses those changes to generate a new immutable state without mutating the original state. !!!


! Real State vs Draft State
| Real State            | Draft State     |
| --------------------- | --------------- |
!| Cannot be mutated     | Can be mutated  |
?| Stored in Redux store | Temporary copy  |
?| Immutable             | Mutable-looking |
| Original data         | Working copy    |


!! An action creator is a function that creates and returns an action object. In Redux Toolkit, action creators are automatically generated by createSlice() and are available through slice.actions.

? the action object is sent to the store through dispatch().
? Action Creator = increment()
Dispatch = dispatch(increment())

! Example:

increment()

returns:

{
  type: "counter/increment"
}

! So:

? Action = { type: "counter/increment" }
? Action Creator = increment()
? Dispatch = dispatch(increment()) ✅

! Action Creator (generated automatically)
? counterSlice.actions.increment

! which is equivalent to:

function increment() {
  return {
    type: "counter/increment"
  };
}

!! When you write
? export const { increment } = counterSlice.actions;

!! you are extracting the generated action creator, not the reducer function.

! So later:

? dispatch(increment());

! means:

dispatch({
  type: "counter/increment"
});


? counterSlice.actions.increment → Action Creator (auto-generated)
? increment() → Returns an action object
? dispatch(increment()) → Sends the action to the store

! Flow
dispatch(action)
      ↓
Store receives action
      ↓
Store calls reducer(state, action)
      ↓
Reducer returns NEW state
      ↓
Store receives returned state
      ↓
Store updates its state

then UI update

! How UI Knows Store Changed?

? useSelector() subscribes to the Redux Store.

const count = useSelector((state) => state.counter.value);

! When this line runs:
useSelector()
     ↓
Subscribes to Store
     ↓
"Notify me whenever state changes"

! Complete Flow

Button Click
      ↓
dispatch(increment())
      ↓
Store receives action
      ↓
Reducer runs
      ↓
Returns new state
      ↓
Store updates state
      ↓
Store notifies subscribers
      ↓
useSelector() detects change
      ↓
Component re-renders
      ↓
Updated UI appears

! The UI re-renders because useSelector() triggers React when the selected state value changes.

! React re-renders the component because useSelector() subscribes to the Redux store. When the selected state value changes, useSelector() detects the change and triggers React to run the component function again, producing updated UI.


! How useSelector() Subscribes to the Store?

When you write:

const count = useSelector(
  (state) => state.counter.value
);

! React-Redux internally does something similar to:

store.subscribe(listener);

Think of it as:

useSelector()
      ↓
store.subscribe()
      ↓
"Call me whenever state changes"

? So useSelector() registers itself as a listener with the Redux store.

! How Does useSelector() Detect Changes?

Suppose:

const count = useSelector(
  (state) => state.counter.value
);

! Initially:

state.counter.value = 0

useSelector stores:

Previous Value = 0
State Changes

! After:

dispatch(increment());

! New state:

state.counter.value = 1

! Store calls all subscribers.

! useSelector runs your selector again:

(state) => state.counter.value

! Result:

New Value = 1

Now it compares:

previousValue === newValue
0 === 1
false

Since the value changed:

useSelector
      ↓
Notifies React
      ↓
Component Re-renders

! Flow
CounterButtons
      ↓ dispatch()
Redux Store
      ↓ update state
CounterDisplay
      ↓ useSelector()
Re-render
      ↓
Updated Count

! In counterSlice.jsx
export const counterSlice = createSlice({
    name: 'counter',
    initialState: {
        value: 0
    },

! Understanding state.counter.value
In Counter.jsx
const count = useSelector(
  (state) => state.counter.value
);

! What is state?

? state is the entire Redux store state.

state = {
  counter: {
    value: 0
  }
}

! Easy Rule
state        → Entire Redux Store

state.counter → Counter Slice State

! state.counter.value → Actual value needed by component

! So in:

const count = useSelector(
  (state) => state.counter.value
);

? state = whole Redux store
? counter = slice name/key in the store
? value = property inside that slice's state
? useSelector returns that value and subscribes to changes in it.


! 1. What is an Action?

An Action is a plain JavaScript object that tells Redux what happened.

Example:

{
  type: "counter/increment"
}

! Meaning:

? "Increment the counter."

! 2. What is type?

Every action must have a type.
type is a property of an action object that describes what happened.

{
  type: "counter/increment"
}

type is like a command name.

counter/increment
counter/decrement
counter/incrementByAmount

! The type field in a Redux action is used to identify what action happened.
! action.type is used to select the correct state update logic.

! Reducers check the type to decide what to do.

! type is a string property inside a Redux action object that uniquely identifies the action. Redux uses the type field to determine which reducer logic should handle the action. In Redux Toolkit, action types are automatically generated in the format sliceName/reducerName, such as "counter/increment".


! 3. What is Payload?

? A payload is extra data sent with an action.

! Example:

? dispatch(incrementByAmount(5))

! Generated action:

{
  type: "counter/incrementByAmount",
  payload: 5
}

Here:

type    = What happened
payload = Data needed

! 4. What is action.payload?

Reducer receives:

incrementByAmount: (state, action) => {
  state.value += action.payload;
}

Suppose:

dispatch(incrementByAmount(5))

! Action becomes:

{
  type: "counter/incrementByAmount",
  payload: 5
}

! Inside reducer:

! action.payload

is:

5

! So:

state.value += 5;

! Visual Flow

dispatch(incrementByAmount(5))
              ↓
Action Created
{
  type: "counter/incrementByAmount",
  payload: 5
}
              ↓
Reducer receives action
              ↓
action.payload = 5
              ↓
state.value += 5

! 5. What is counterSlice.reducer?

When you create a slice:

const counterSlice = createSlice({
  name: "counter",
  initialState: { value: 0 },
  reducers: {
    increment: (state) => {
      state.value++;
    }
  }
});

!!!! counterSlice is an object. !!!!

?? It contains:

{
  name: "counter",
  actions: {...},
  reducer: function
}

! counterSlice.actions

? Contains action creators:

counterSlice.actions.increment
counterSlice.actions.decrement
counterSlice.actions.incrementByAmount

! counterSlice.reducer

? Contains the reducer function generated by Redux Toolkit.

counterSlice.reducer

is roughly:

function reducer(state, action) {
  / update state based on action.type
}

! This is the function the store uses.

! Why Export It?
export default counterSlice.reducer;

? Then in store:

import counterReducer from "./counterSlice";

configureStore({
  reducer: {
    counter: counterReducer
  }
});

! So:

counterSlice.reducer
        ↓
counterReducer
        ↓
!Store uses it to update state

! Quick Summary

| Term                 | Meaning                                           |
| -------------------- | ------------------------------------------------- |
!| Action               | Object describing what happened                   |
?| type                 | Name of the action                                |
| payload              | Extra data sent with the action                   |
| action.payload       | Accesses that extra data inside reducer           |
| counterSlice.actions | Auto-generated action creators                    |
!| counterSlice.reducer | Auto-generated reducer function used by the store |

! Example
dispatch(incrementByAmount(10))

Creates:
{
  type: "counter/incrementByAmount",
  payload: 10
}

Reducer:
incrementByAmount: (state, action) => {
  state.value += action.payload;
}

Result:
action.payload = 10
state.value += 10

!-------------------------------------------
! export const {increment, decrement, incrementByAmount} = counterSlice.actions
! export default counterSlice.reducer  explain these two exports

These are the two most important exports from a Redux Toolkit slice.

! 1. Exporting Actions
export const {
  increment,
  decrement,
  incrementByAmount
} = counterSlice.actions;

! What is counterSlice.actions?

? When createSlice() runs, Redux Toolkit automatically creates action creator functions.

? counterSlice.actions

! contains:

{
  increment: function,
  decrement: function,
  incrementByAmount: function
}

! Destructuring
const {
  increment,
  decrement,
  incrementByAmount
} = counterSlice.actions;

! is equivalent to:

const increment = counterSlice.actions.increment;
const decrement = counterSlice.actions.decrement;
const incrementByAmount =
      counterSlice.actions.incrementByAmount;

! Why Export Them?

? So other files can use them.

export const {
  increment,
  decrement,
  incrementByAmount
} = counterSlice.actions;

! Now in a component:

import {
  increment,
  decrement,
  incrementByAmount
} from "./counterSlice";

! Usage:

dispatch(increment());
dispatch(decrement());
dispatch(incrementByAmount(5));

! What Do They Return?
increment()
increment()

! returns:

{
  type: "counter/increment"
}
decrement()
decrement()

! returns:

{
  type: "counter/decrement"
}
incrementByAmount(5)
incrementByAmount(5)

! returns:

{
  type: "counter/incrementByAmount",
  payload: 5
}

! 2. Exporting Reducer
? export default counterSlice.reducer;

! What is counterSlice.reducer?

? Redux Toolkit automatically creates a reducer function from your reducers.

? counterSlice.reducer

is roughly:

function reducer(state, action) {
  switch (action.type) {
    case "counter/increment":
      / update state
      break;

    case "counter/decrement":
      / update state
      break;

    case "counter/incrementByAmount":
      / update state
      break;

    default:
      return state;
  }
}

! You don't write this manually—RTK generates it.

! Why Export It?

?? The Redux Store needs a reducer.

! Store file:

import counterReducer from "./counterSlice";

configureStore({
  reducer: {
    counter: counterReducer
  }
});

! Here:

? counterReducer

! is actually:

? counterSlice.reducer

! Easy Memory Trick

counterSlice.actions
       ↓
Creates Action Objects
       ↓
Used with dispatch()

counterSlice.reducer
       ↓
Processes Action Objects
       ↓
Updates State

! Complete Flow

counterSlice.actions.increment()
                ↓
{
  type: "counter/increment"
}
                ↓
dispatch()
                ↓
Store
                ↓
counterSlice.reducer
                ↓
State Updated
                ↓
UI Re-renders

! One-Line Interview Answer

! counterSlice.actions exports action creator functions
(increment, decrement, incrementByAmount).

! counterSlice.reducer exports the reducer function that 
handles those actions and updates the Redux state.


!! 1. counterSlice.actions → Import in Components !!
import { increment, decrement, incrementByAmount }
from "../features/counter/counterSlice";

! Use with dispatch():

dispatch(increment());
dispatch(decrement());
dispatch(incrementByAmount(5));

! Purpose: Creates action objects.

!! 2. counterSlice.reducer → Import in Store !!
import counterReducer
from "../features/counter/counterSlice";

! Use in:

configureStore({
  reducer: {
    counter: counterReducer
  }
});

! Purpose: Updates state when actions are dispatched.

! Easy Memory
? actions  → Import in Components → dispatch()

? reducer  → Import in Store → manage state

? increment()  → creates action

? counterReducer → handles action & updates state


! What is a Reducer?

? A Reducer is a function that receives:

? Current State
? Action

! and returns the new updated state.

! Syntax
(state, action) => newState

? state → Current state
? action → Dispatched action
? return → New state

! Redux Toolkit Example
const counterSlice = createSlice({
  name: "counter",
  initialState: {
    value: 0
  },
  reducers: {
    increment: (state) => {
      state.value++;
    }
  }
});

! This:

increment: (state) => {
  state.value++;
}

! is a case reducer.

! Redux Toolkit combines all case reducers and creates a slice reducer:

? counterSlice.reducer

!! which is passed to the store.


! Why is it called Reducer?

Because it takes:

? Current State + Action

? and reduces them into:

New State

! Flow

dispatch(increment())
          ↓
Action
{
  type: "counter/increment"
}
          ↓
Reducer
(state, action)
          ↓
New State
{
  value: 1
}
          ↓
Store Updates State

! Real Example

! Current state:

{
  value: 5
}

! Action:

{
  type: "counter/increment"
}

! Reducer:

increment: (state) => {
  state.value++;
}

! New state:

{
  value: 6
}

! Store saves this new state.

!! Types of Reducers in Redux Toolkit

! Case Reducer
increment: (state) => {
  state.value++;
}

! Handles one specific action.

!! Slice Reducer
counterSlice.reducer

!! Handles all actions of the counter slice.

!! Used in: !!

configureStore({
  reducer: {
    counter: counterSlice.reducer
  }
});


! A reducer is a pure function that takes the current state and an action as arguments and returns a new state. In Redux Toolkit, reducers define how the state should change in response to dispatched actions. The store calls reducers whenever an action is dispatched, and the returned state becomes the new store state.

incrementByAmount: (state, action) => {
    state.value += action.payload;
}

! This is a Case Reducer. ✅

! Why?

? Because it is defined inside the reducers object of createSlice():
const counterSlice = createSlice({
  name: "counter",
  initialState: { value: 0 },
  reducers: {
    increment: (state) => {
      state.value++;
    },

    incrementByAmount: (state, action) => {
      state.value += action.payload;
    }
  }
});

! Redux Toolkit combines all case reducers into a single slice reducer (counterSlice.reducer).

? Inside the reducers object of createSlice(), every function is a Case Reducer.

reducers object
      ↓
increment      → Case Reducer
decrement      → Case Reducer
incrementByAmount → Case Reducer
      ↓
createSlice()
      ↓
counterSlice.reducer
      ↓
Slice Reducer
      ↓
Store

! Every function defined inside the reducers object of createSlice() is called a case reducer. Each case reducer handles a specific action type. Redux Toolkit automatically combines all case reducers into a single slice reducer, which is then provided to the Redux store.


! What is a Pure Function?

? A Pure Function is a function that:

? Always returns the same output for the same input.
? Does not modify anything outside the function (no side effects).

! Example of a Pure Function
function add(a, b) {
  return a + b;
}
add(2, 3); // 5
add(2, 3); // 5
add(2, 3); // 5

! Same inputs → Same output.

! Also, it doesn't change any external variable.

✅ Pure Function

! Example of an Impure Function
let count = 0;

function increment() {
  count++;
  return count;
}

! Output:

increment(); // 1
increment(); // 2
increment(); // 3

! Same input (no input) but different outputs.

! Also modifies external variable count.

! Why are Reducers supposed to be Pure?

Redux reducers should:

(state, action) => newState

! Given the same state and action, they should always produce the same result.

! Example:

function counterReducer(state, action) {
  switch (action.type) {
    case "increment":
      return {
        value: state.value + 1
      };

    default:
      return state;
  }
}

! Input:

state = { value: 5 }
action = { type: "increment" }

! Output will always be:

{ value: 6 }

✅ Pure

! Side Effects (Not Allowed in Reducers)
? fetch("https://api.com/users");
? localStorage.setItem("name", "Touseef");
? setTimeout(() => {}, 1000);
? Math.random();

! These are side effects and should not be inside reducers.

Redux Toolkit Note

You write:

increment: (state) => {
  state.value++;
}

It looks like mutation, but Redux Toolkit uses Immer internally to create a new state object.

So the reducer remains pure from Redux's perspective.

A pure function is a function that always returns the same output for the same input and does not produce side effects or modify external state. Redux reducers are expected to be pure functions because they must consistently generate the same next state when given the same current state and action.


! increment: (state) => { state.value++; } where the action parameter ?

? In Redux, a reducer normally receives two parameters:

(state, action) => {
  / reducer logic
}

! Example:

incrementByAmount: (state, action) => {
  state.value += action.payload;
}

!! Here you need action because you're using action.payload. !!

!! Then why is action missing here? !!
increment: (state) => {
  state.value++;
}

! Because the reducer doesn't need anything from the action object.

? Redux Toolkit still calls it with both arguments:

increment(state, action)

? but since action is not used, we simply omit it.

! You could write:

increment: (state, action) => {
  state.value++;
}

! and it would still work.

!! What does the action look like?

? When you dispatch:

dispatch(increment());

? Redux Toolkit creates:

{
  type: "counter/increment"
}

! and internally calls:

increment(
  state,
  {
    type: "counter/increment"
  }
);

! Since you're not using the action, you don't need to declare the parameter.

! Compare
? No payload needed
increment: (state) => {
  state.value++;
}

! Action:

{
  type: "counter/increment"
}

! No need to access it.


!! What is type in Redux? !!

? type is a property of an action object that describes what happened.

! Example:

{
  type: "counter/increment"
}

! Here:

type: "counter/increment"

! tells Redux:

"The increment action has been dispatched."

! Why is type needed?

! Redux uses the type to determine which reducer logic should run.

! Example:

dispatch(increment());

! Redux Toolkit creates:

{
  type: "counter/increment"
}

? Redux sees:

"counter/increment"

! and runs the matching case reducer:

increment: (state) => {
  state.value++;
}

! How is type created?

In your slice:

const counterSlice = createSlice({
! name: "counter",
  reducers: {
    increment: (state) => {
      state.value++;
    }
  }
});

! Redux Toolkit automatically generates:

sliceName/reducerName

! So:

name: "counter"
increment

! becomes:

type: "counter/increment"


! Note - name
name: "counter"

? Name of the slice.
? Used to generate action types.

! Example:
increment()

! creates:
{
  type: "counter/increment"
}


!! Action Object Examples

! Without Payload
dispatch(increment());

! Action:

{
  type: "counter/increment"
}

! With Payload
dispatch(incrementByAmount(5));

! Action:

{
  type: "counter/incrementByAmount",
  payload: 5
}


! type is a string property inside a Redux action object that uniquely identifies the action. Redux uses the type field to determine which reducer logic should handle the action. In Redux Toolkit, action types are automatically generated in the format sliceName/reducerName, such as "counter/increment".


!! What is a Redux State Slice?

A Redux State Slice is a portion (piece) of the Redux store state that is managed by a specific slice reducer.
? A Redux state slice is a part of the Redux store that stores data for one feature.

! Example:
? state.counter = { value: 0 }

!! Here counter is the state slice. !!

! Difference between Counter Slice and Counter State Slice
| Counter Slice                            | Counter State Slice        |
| ---------------------------------------- | -------------------------- |
| Created using `createSlice()`            | Actual data in Redux store |
| Contains reducers, actions, initialState | Only contains state values |
| Example: `counterSlice`                  | Example: `{ value: 0 }`    |
| Logic + structure                        | Only data                  |

! Example
const counterSlice = createSlice({
  name: "counter",
  initialState: { value: 0 },
  reducers: {
    increment: (state) => {
      state.value++;
    }
  }
});

! In:

reducer: {
  counter: counterSlice.reducer
}

! counter is the Redux state slice (the key in the store).
! counterSlice.reducer is the slice reducer that manages that state slice.

The resulting store state looks like:
{
  counter: {
    value: 0
  }
}

! where state.counter is the Redux state slice.

!! Accessing a State Slice
const count = useSelector(
  state => state.counter.value
);

! Here:

! state = entire Redux store state

! state.counter = counter state slice

! state.counter.value = specific value inside that slice


! Why do we create a Slice in Redux Toolkit?

? A slice groups everything related to one feature in a single place:

State
Reducers
Action Creators

! Without createSlice(), you would have to create all of these separately.

! With createSlice()
const counterSlice = createSlice({
  name: "counter",
  initialState: {
    value: 0
  },
  reducers: {
    increment: (state) => {
      state.value++;
    }
  }
});

! Redux Toolkit automatically creates:

✓ State
✓ Reducer
✓ Action Creator
✓ Action Type

! What does a Slice contain?
const counterSlice = createSlice({
  name: "counter",
  initialState: { value: 0 },
  reducers: {
    increment: (state) => {
      state.value++;
    }
  }
});

! Creates:

? 1. Initial State
{ value: 0 }

? 2. Case Reducer
increment: (state) => {
  state.value++;
}

? 3. Action Creator
increment()

? 4. Action Type
"counter/increment"

? 5. Slice Reducer
counterSlice.reducer

! Real Project Example

You might have multiple features:

User Feature
Cart Feature
Counter Feature
Product Feature

! Create separate slices:

userSlice.js
cartSlice.js
counterSlice.js
productSlice.js

! Each slice manages its own state and logic.
*/